---
# necessary steps to configure the role

- name: install base condarc
  become: yes
  become_method: sudo
  become_user: "{{ galaxy_user }}"
  copy: src={{ item }} dest="~/.{{ item }}"
  with_items:
    - condarc
  when: miniconda_add_condarc

- name: add miniconda to the PATH
  become: yes
  become_method: sudo
  become_user: "{{ galaxy_user }}"
  lineinfile:
    dest: "{{ miniconda_rcfile }}"
    line: export PATH={{ miniconda_home }}/bin:$PATH
    state: present
  when: miniconda_modify_path

- name: UpdateDB
  become_method: sudo
  become: yes
  remote_user: "{{ remote_user }}"
  command: updatedb

- name: Copy over Good libread
  become_method: sudo
  become: yes
  remote_user: "{{ remote_user }}"
  copy:
    remote_src: yes
    src: /usr/lib64/libreadline.so.6
    dest: "{{ miniconda_lib }}"
    owner: galaxy
    group: galaxy
    mode: 777
  notify:
    - run ldconfig

- name: Install uWSGI
  remote_user: "{{ remote_user }}"
  shell: "{{ miniconda_home }}/bin/conda config --add channels conda-forge && {{ miniconda_home }}/bin/conda install uwsgi"


