---
# necessary steps to configure the role

- name: install base condarc
  become: yes
  become_method: sudo
  become_user: "{{ galaxy_user }}"
  copy: src={{ item }} dest="~/.{{ item }}"
  with_items:
    - condarc
  when: miniconda_add_condarc

- name: add miniconda to the PATH
  become: yes
  become_method: sudo
  become_user: "{{ galaxy_user }}"
  lineinfile:
    dest: "{{ miniconda_rcfile }}"
    line: export PATH={{ miniconda_home }}/bin:$PATH
    state: present
  when: miniconda_modify_path


- name: create environment
  remote_user: "{{ remote_user }}"
  shell: "{{ miniconda_home }}/bin/conda create --yes -q -n {{ item.name }}  {{ item.pkgs }}"
  with_items: " {{ miniconda_environments }} "


- name: Set enviroment ownership back to Galaxy
  remote_user: "{{ remote_user }}"
  file:
    path: "{{ miniconda_home }}envs/{{ item.name }}"
    owner: "{{ galaxy_user }}"
    group: "{{ galaxy_user }}"
    recurse: yes
  with_items: " {{ miniconda_environments }} "

