---
# necessary steps to deploy the role.

- name: check if already installed
#  become: yes
#  become_method: sudo
  become_user: "{{ galaxy_user }}"
#  remote_user: "{{ remote_user }}"
  stat: path={{ miniconda_home }}/bin/conda
  register: bin_conda
  changed_when: bin_conda.stat.exists == False

- name: download miniconda installer
  become_user: "{{ galaxy_user }}"
  get_url:
    url={{ miniconda_url }}
    dest=/tmp/miniconda.sh
    mode=0755
  register: miniconda_downloaded
  when: bin_conda.stat.exists == False

- name: install miniconda
  become: yes
  become_method: sudo
  become_user: "{{ galaxy_user }}"
  shell: "/tmp/miniconda.sh -b -p {{ miniconda_home }} creates={{ miniconda_home }} executable=/bin/bash"
  register: miniconda_installed
  when: miniconda_downloaded is success
  notify:
    - remove miniconda setup script
    - update conda to latest version


- name: Set Conda dir owerniship
  remote_user: "{{ remote_user }}"
  file:
    path: "{{ miniconda_home }}"
    owner: "{{ galaxy_user }}"
    group: "{{ galaxy_user }}"
    recurse: yes


- name: Set owerniship
  remote_user: "{{ remote_user }}"
  file:
    path: "{{ host_tool_dependency_dir }}"
    owner: "{{ galaxy_user }}"
    group: "{{ galaxy_user }}"
    recurse: yes

- name: Install virtualenv on Conda root
  shell: "{{ miniconda_home }}/bin/conda install virtualenv"

- name: Set virtualenv ownership
  file:
    path: "/srv/galaxy/tool-dependency/_conda/lib/python2.7/site-packages"
    owner: "{{ galaxy_user }}"
    group: "{{ galaxy_user }}"
    recurse: yes