---
- name: Install Galaxy and dependencies
  hosts: galaxyservers
  become_method: sudo
  become: yes
  remote_user: "{{ remote_user }}"
  roles:
    - galaxyprojectdotorg.postgresql
    - galaxyprojectdotorg.nginx

- name: Configure PostgreSQL access
  hosts: galaxyservers
  become: yes
  become_user: postgres
  remote_user: "{{ remote_user }}"
  roles:
    - natefoo.postgresql_objects

- name: Move PosgreSQL data Dir
  hosts: galaxyservers
  become_method: sudo
  become: yes
  remote_user: "{{ remote_user }}"
  roles:
    - move.postgres

- name: Install and configure Galaxy
  hosts: galaxyservers
  become: yes
  become_user: "{{ galaxy_user }}"
  remote_user: "{{ remote_user }}"
  roles:
    - galaxyprojectdotorg.galaxy

- name: Install and configure supervisor
  hosts: galaxyservers
  remote_user: "{{ remote_user }}"
  roles:
    - supervisor

- name: Install Galaxy dependencies on virtualenv
  hosts: galaxyservers
  become: yes
  become_user: "{{ galaxy_user }}"
  tasks:
    - name: Install Galaxy depencencies on virtualenv
      shell: source "{{ galaxy_server_dir }}"/.venv/bin/activate && pip install "{{ item }}"
      with_items:
        - uwsgi
