---
- name: Galaxy Status
  hosts: galaxyservers
  become: yes
  tasks:
    - name: Start Supervisord
      shell: source "{{ galaxy_server_dir }}"/.venv/bin/activate && supervisord -c  /etc/supervisor/conf.d/galaxy.conf
      register: status
      tags:
        - supervisor-start

    - name: Stop Supervisord
      shell: source "{{ galaxy_server_dir }}"/.venv/bin/activate && supervisorctl -c  /etc/supervisor/conf.d/galaxy.conf shutdown
      register: status
      tags:
        - supervisor-stop

    - name: start Galaxy
      shell: 'source "{{ galaxy_server_dir }}"/.venv/bin/activate && supervisorctl -c  /etc/supervisor/conf.d/galaxy.conf start main:'
      register: status
      tags:
        - galaxy-start

    - name: start handlers
      shell: 'source "{{ galaxy_server_dir }}"/.venv/bin/activate && supervisorctl -c  /etc/supervisor/conf.d/galaxy.conf start handler:'
      register: status
      tags:
        - handler-start

    - name: stop handlers
      shell: 'source "{{ galaxy_server_dir }}"/.venv/bin/activate && supervisorctl -c  /etc/supervisor/conf.d/galaxy.conf stop handler:'
      register: status
      tags:
        - handler-stop

    - name: restart handlers
      shell: 'source "{{ galaxy_server_dir }}"/.venv/bin/activate && supervisorctl -c  /etc/supervisor/conf.d/galaxy.conf restart handler:'
      register: status
      tags:
        - handler-restart

    - name: Check if Galaxy it is up
      shell: 'source "{{ galaxy_server_dir }}"/.venv/bin/activate && supervisorctl -c  /etc/supervisor/conf.d/galaxy.conf status main:'
      register: status
      tags:
        - galaxy-status

    - name: Stop Galaxy
      shell: 'source "{{ galaxy_server_dir }}"/.venv/bin/activate && supervisorctl -c  /etc/supervisor/conf.d/galaxy.conf stop main:'
      register: status
      tags:
        - galaxy-stop

    - name: Restart Galaxy
      shell: 'source "{{ galaxy_server_dir }}"/.venv/bin/activate && supervisorctl -c  /etc/supervisor/conf.d/galaxy.conf restart main:'
      register: status
      tags:
        - galaxy-restart

    - name: Restart PostgreSQL
      shell: /etc/init.d/postgresql-9.4 restart
      register: status
      tags:
        - postgres-restart

    - name: Stop PostgreSQL
      shell: /etc/init.d/postgresql-9.4 stop
      register: status
      tags:
        - postgres-stop

    - name: Start PostgreSQL
      shell: /etc/init.d/postgresql-9.4 start
      register: status
      tags:
        - postgres-start

    - name: Reload PostgreSQL
      shell: /etc/init.d/postgresql-9.4 reload
      register: status
      tags:
        - postgres-reload

    - name: Reload ngnix
      service: name=nginx state=reloaded
      tags:
        - proxy-reload

    - debug: msg="{{ status.stdout_lines }}"
      tags: stat
